name: execute python program
on:
  push:
    branches:
      - main
jobs:
  run_py_file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout python code
        uses: actions/checkout@v6.0.2
      - name: run python file
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.11'
      - name: run python code
        run: python app.py
        
