name: Execute python program
on:
  push:
    branches:
      - main
jobs:
  run_py_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v3
      - name: run python code
        run: python app.py
        

        
